package config;
// Generated 17 Apr, 2020 3:49:20 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Doctor generated by hbm2java
 */
public class Doctor  implements java.io.Serializable {


     private Integer docId;
     private String docName;
     private String docAddress;
     private Date docDob;
     private int docAge;
     private String docMobileno;
     private int docWeight;
     private String docBloodgrp;
     private String docYoe;
     private String docSpeciality;
     private String docAchievements;
     private String docEmail;

    public Doctor() {
    }

    public Doctor(String docName, String docAddress, Date docDob, int docAge, String docMobileno, int docWeight, String docBloodgrp, String docYoe, String docSpeciality, String docAchievements, String docEmail) {
       this.docName = docName;
       this.docAddress = docAddress;
       this.docDob = docDob;
       this.docAge = docAge;
       this.docMobileno = docMobileno;
       this.docWeight = docWeight;
       this.docBloodgrp = docBloodgrp;
       this.docYoe = docYoe;
       this.docSpeciality = docSpeciality;
       this.docAchievements = docAchievements;
       this.docEmail = docEmail;
    }
   
    public Integer getDocId() {
        return this.docId;
    }
    
    public void setDocId(Integer docId) {
        this.docId = docId;
    }
    public String getDocName() {
        return this.docName;
    }
    
    public void setDocName(String docName) {
        this.docName = docName;
    }
    public String getDocAddress() {
        return this.docAddress;
    }
    
    public void setDocAddress(String docAddress) {
        this.docAddress = docAddress;
    }
    public Date getDocDob() {
        return this.docDob;
    }
    
    public void setDocDob(Date docDob) {
        this.docDob = docDob;
    }
    public int getDocAge() {
        return this.docAge;
    }
    
    public void setDocAge(int docAge) {
        this.docAge = docAge;
    }
    public String getDocMobileno() {
        return this.docMobileno;
    }
    
    public void setDocMobileno(String docMobileno) {
        this.docMobileno = docMobileno;
    }
    public int getDocWeight() {
        return this.docWeight;
    }
    
    public void setDocWeight(int docWeight) {
        this.docWeight = docWeight;
    }
    public String getDocBloodgrp() {
        return this.docBloodgrp;
    }
    
    public void setDocBloodgrp(String docBloodgrp) {
        this.docBloodgrp = docBloodgrp;
    }
    public String getDocYoe() {
        return this.docYoe;
    }
    
    public void setDocYoe(String docYoe) {
        this.docYoe = docYoe;
    }
    public String getDocSpeciality() {
        return this.docSpeciality;
    }
    
    public void setDocSpeciality(String docSpeciality) {
        this.docSpeciality = docSpeciality;
    }
    public String getDocAchievements() {
        return this.docAchievements;
    }
    
    public void setDocAchievements(String docAchievements) {
        this.docAchievements = docAchievements;
    }
    public String getDocEmail() {
        return this.docEmail;
    }
    
    public void setDocEmail(String docEmail) {
        this.docEmail = docEmail;
    }




}


